<?php
require_once __DIR__ . '/layout.php';
$published = scalar("SELECT COUNT(*) FROM public_announcements WHERE status='published'", 0);
$advisories = scalar("SELECT COUNT(*) FROM public_announcements WHERE announcement_type='traffic advisory'", 0);
$activities = scalar("SELECT COUNT(*) FROM public_announcements WHERE announcement_type='tmo activity'", 0);
$notices = scalar("SELECT COUNT(*) FROM public_announcements WHERE announcement_type='public notice'", 0);
$posts = fetch_all("SELECT a.*, u.full_name AS created_by_name FROM public_announcements a LEFT JOIN users u ON u.user_id=a.created_by ORDER BY a.publish_date DESC LIMIT 50");
page_start('Public Website', 'public', 'Search public posts...');
?>
<div class="d-flex justify-content-between flex-wrap mb-4 gap-2"><div><h3 class="page-title">Public Website Management</h3><p class="page-sub">Publish TMO advisories, activities, events, and public notices for Nasugbu motorists.</p></div><button class="btn btn-primary" disabled><i class="bi bi-plus-lg me-1"></i>New Public Notice</button></div>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="stat-card"><div class="stat-icon tone-primary"><i class="bi bi-megaphone"></i></div><div class="stat-label">Published Posts</div><div class="stat-value"><?= num($published) ?></div></div></div><div class="col-md-3"><div class="stat-card"><div class="stat-icon tone-warning"><i class="bi bi-cone-striped"></i></div><div class="stat-label">Traffic Advisories</div><div class="stat-value"><?= num($advisories) ?></div></div></div><div class="col-md-3"><div class="stat-card"><div class="stat-icon tone-success"><i class="bi bi-calendar-event"></i></div><div class="stat-label">TMO Activities</div><div class="stat-value"><?= num($activities) ?></div></div></div><div class="col-md-3"><div class="stat-card"><div class="stat-icon tone-danger"><i class="bi bi-exclamation-triangle"></i></div><div class="stat-label">Public Notices</div><div class="stat-value"><?= num($notices) ?></div></div></div></div>
<div class="row g-3"><div class="col-lg-7"><div class="section-card"><div class="section-head"><h6>Public Posts</h6><span class="tag tag-success">Website active</span></div><?php if (!$posts): empty_state('No public announcements found. Add posts to public_announcements.'); else: foreach($posts as $p): ?><div class="border-bottom py-3"><div class="d-flex justify-content-between"><strong><?= esc($p['title']) ?></strong><span class="tag <?= tag_class($p['status']) ?>"><?= esc($p['status']) ?></span></div><small class="text-muted"><?= esc($p['announcement_type']) ?> • <?= esc($p['publish_date']) ?></small><p class="mb-0 mt-2 text-muted small"><?= esc(mb_strimwidth($p['content'],0,180,'...')) ?></p></div><?php endforeach; endif; ?></div></div><div class="col-lg-5"><div class="section-card"><div class="section-head"><h6>Public Website Preview</h6></div><div class="p-4 rounded" style="background:#0f4c81;color:white"><h4>TRAVIS</h4><p class="mb-0">Traffic Monitoring and Decision Support System</p></div><div class="mt-3"><h6>Sections</h6><ul class="text-muted small"><li>About TMO</li><li>Latest Announcements</li><li>Traffic Advisories</li><li>Public Notices</li><li>TMO Activities</li><li>Contact Information</li></ul></div></div></div></div>
<?php page_end(); ?>
