import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import api from '../../api/axiosConfig';

type Notice = { id: string; title: string; detail: string; date: string; type: 'payment' | 'violation' };
export default function TreasurerNotifications() {
  const [items, setItems] = useState<Notice[]>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { const [p, v] = await Promise.all([api.get('get_payments.php'), api.get('get_violations.php', { params: { limit: 15 } })]); const payments = (p.data.data || []).slice(0, 10).map((x: any) => ({ id: `p-${x.payment_id}`, title: 'Payment received', detail: `${x.ticket_number} · ₱${Number(x.amount_paid).toLocaleString('en-PH')}`, date: x.payment_date, type: 'payment' as const })); const violations = (v.data.data || []).filter((x: any) => x.status === 'pending' || x.status === 'overdue').slice(0, 10).map((x: any) => ({ id: `v-${x.violation_id}`, title: x.status === 'overdue' ? 'Overdue payment' : 'Payment pending', detail: `${x.ticket_number} · ${x.plate_number}`, date: x.violation_date || x.created_at, type: 'violation' as const })); setItems([...payments, ...violations].sort((a, b) => String(b.date).localeCompare(String(a.date))).slice(0, 20)); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]); if (loading) return <View style={styles.center}><ActivityIndicator color="#087D78" /></View>;
  return <ScrollView contentContainerStyle={styles.page} refreshControl={<RefreshControl refreshing={false} onRefresh={load} />}><Text style={styles.title}>Collection Updates</Text><Text style={styles.sub}>Recent payments and violations awaiting collection.</Text>{items.length === 0 ? <Text style={styles.empty}>You are all caught up.</Text> : items.map(x => <View key={x.id} style={styles.card}><View style={[styles.icon, { backgroundColor: x.type === 'payment' ? '#DDF6EC' : '#FEF0D8' }]}><Ionicons name={x.type === 'payment' ? 'checkmark-circle-outline' : 'time-outline'} size={21} color={x.type === 'payment' ? '#15966F' : '#EB941F'} /></View><View style={{ flex: 1 }}><Text style={styles.itemTitle}>{x.title}</Text><Text style={styles.detail}>{x.detail}</Text><Text style={styles.date}>{x.date}</Text></View></View>)}</ScrollView>;
}
const styles = StyleSheet.create({ page: { padding: 18, paddingBottom: 35 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, title: { fontSize: 24, fontWeight: '800', color: '#10202C' }, sub: { color: '#64748B', marginTop: 4, marginBottom: 18 }, card: { flexDirection: 'row', gap: 12, backgroundColor: '#FFF', borderRadius: 14, padding: 15, marginBottom: 10, borderWidth: 1, borderColor: '#E2E8F0' }, icon: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, itemTitle: { fontWeight: '800', color: '#10202C' }, detail: { color: '#475569', marginTop: 4 }, date: { color: '#94A3B8', fontSize: 11, marginTop: 5 }, empty: { backgroundColor: '#FFF', padding: 30, borderRadius: 14, color: '#64748B', textAlign: 'center' } });
