import React, { useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';
import { getStoredUser, TravisUser } from '../../utils/session';
import { Ionicons } from '@expo/vector-icons';
import { TREASURY } from '../../constants/treasury-theme';

export default function TreasurerProfile() {
  const [user, setUser] = useState<TravisUser | null>(null);
  useEffect(() => { getStoredUser().then(setUser); }, []);
  if (!user) return <View style={styles.center}><ActivityIndicator color="#087D78" /></View>;
  const field = (label: string, value: string) => <View style={styles.field}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.page}><View style={styles.hero}><View style={styles.heroGlow} /><View style={styles.avatar}><Text style={styles.initials}>{user.full_name.split(/\s+/).map(v => v[0]).slice(0, 2).join('').toUpperCase()}</Text></View><Text style={styles.name}>{user.full_name}</Text><Text style={styles.role}>{user.role} · Treasury & Collection Portal</Text><View style={styles.session}><Ionicons name="shield-checkmark" size={14} color="#A7F3D0" /><Text style={styles.sessionText}>Secure session active</Text></View></View><View style={styles.card}>{field('Email address', user.email)}{field('Access role', user.role)}{field('User ID', String(user.user_id))}<View style={styles.notice}><Ionicons name="information-circle-outline" size={20} color={TREASURY.blue} /><Text style={styles.note}>Treasurer profiles are view-only. Contact an administrator to update account details or reset your password.</Text></View></View></ScrollView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: TREASURY.bg }, page: { padding: 18, paddingBottom: 38 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, hero: { backgroundColor: TREASURY.navy, padding: 28, borderRadius: 24, alignItems: 'center', overflow: 'hidden' }, heroGlow: { position: 'absolute', width: 180, height: 180, borderRadius: 90, backgroundColor: 'rgba(56,189,248,.12)', right: -55, top: -70 }, avatar: { width: 74, height: 74, borderRadius: 24, backgroundColor: TREASURY.cyan, alignItems: 'center', justifyContent: 'center' }, initials: { color: TREASURY.navy, fontSize: 23, fontWeight: '900' }, name: { color: '#FFF', fontSize: 21, fontWeight: '900', marginTop: 13 }, role: { color: '#C9D8EA', marginTop: 4, fontSize: 11 }, session: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: 'rgba(22,163,106,.2)', borderRadius: 20, paddingHorizontal: 10, paddingVertical: 6, marginTop: 15 }, sessionText: { color: '#D1FAE5', fontSize: 10, fontWeight: '800' }, card: { backgroundColor: '#FFF', borderRadius: 20, padding: 18, marginTop: 14, borderWidth: 1, borderColor: TREASURY.line }, field: { paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: '#E2E8F0' }, label: { color: '#64748B', fontSize: 10, textTransform: 'uppercase', letterSpacing: .8 }, value: { color: '#10202C', fontWeight: '800', marginTop: 5 }, notice: { flexDirection: 'row', gap: 10, backgroundColor: '#EFF6FF', borderRadius: 14, padding: 13, marginTop: 18 }, note: { flex: 1, color: '#526B64', lineHeight: 18, fontSize: 11 } });
