<?php
require_once __DIR__ . '/layout.php';
$collectedToday = scalar("SELECT COALESCE(SUM(amount_paid),0) FROM payments WHERE DATE(payment_date)=CURDATE() AND payment_status='completed'", 0);
$thisWeek = scalar("SELECT COALESCE(SUM(amount_paid),0) FROM payments WHERE YEARWEEK(payment_date,1)=YEARWEEK(CURDATE(),1) AND payment_status='completed'", 0);
$pendingAmount = scalar("SELECT COALESCE(SUM(v.penalty_amount),0) FROM violations v WHERE v.status IN ('pending','overdue')", 0);
$payments = fetch_all("SELECT p.*, v.ticket_number, v.plate_number, v.driver_name, u.full_name AS received_by_name FROM payments p JOIN violations v ON v.violation_id=p.violation_id LEFT JOIN users u ON u.user_id=p.received_by ORDER BY p.payment_date DESC LIMIT 50");
page_start('Payments', 'payments', 'Search payments...');
?>
<div class="d-flex justify-content-between flex-wrap mb-4 gap-2"><div><h3 class="page-title">Payments</h3><p class="page-sub">Treasury receipt validation, payment recording, and reconciliation</p></div><button class="btn btn-primary" disabled><i class="bi bi-download me-1"></i>Export Ledger</button></div>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="stat-card"><div class="stat-icon tone-success"><i class="bi bi-cash-stack"></i></div><div class="stat-label">Collected Today</div><div class="stat-value"><?= short_money($collectedToday) ?></div></div></div><div class="col-md-4"><div class="stat-card"><div class="stat-icon tone-primary"><i class="bi bi-graph-up"></i></div><div class="stat-label">This Week</div><div class="stat-value"><?= short_money($thisWeek) ?></div></div></div><div class="col-md-4"><div class="stat-card"><div class="stat-icon tone-warning"><i class="bi bi-hourglass-split"></i></div><div class="stat-label">Pending Settlement</div><div class="stat-value"><?= short_money($pendingAmount) ?></div></div></div></div>
<div class="section-card mb-4"><div class="section-head"><h6>Receipt Recording Options</h6></div><div class="row g-3"><div class="col-md-6"><button class="btn btn-primary w-100" disabled><i class="bi bi-upc-scan me-1"></i> Scan Issued Receipt</button><small class="text-muted d-block mt-2">OCR integration placeholder.</small></div><div class="col-md-6"><button class="btn btn-light w-100" disabled><i class="bi bi-keyboard me-1"></i> Manual Encoding</button><small class="text-muted d-block mt-2">Manual payment form placeholder.</small></div></div></div>
<div class="section-card"><div class="section-head"><h6>Payment Transactions</h6></div><?php if (!$payments): empty_state('No payment transactions found.'); else: ?><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Payment ID</th><th>Ticket</th><th>Driver/Plate</th><th>Amount</th><th>Method</th><th>Date</th><th>Status</th><th>Received By</th></tr></thead><tbody><?php foreach($payments as $p): ?><tr><td class="fw-semibold">PAY-<?= esc($p['payment_id']) ?></td><td><?= esc($p['ticket_number']) ?></td><td><?= esc($p['driver_name']) ?><br><small class="text-muted"><?= esc($p['plate_number']) ?></small></td><td class="fw-semibold"><?= peso($p['amount_paid']) ?></td><td><?= esc($p['payment_method']) ?></td><td class="text-muted"><?= esc($p['payment_date']) ?></td><td><span class="tag <?= tag_class($p['payment_status']) ?>"><?= esc($p['payment_status']) ?></span></td><td><?= esc($p['received_by_name'] ?? 'N/A') ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div>
<?php page_end(); ?>
